server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:kakao;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO